name: Veracode Build Artifact

run-name: Veracode Build Artifact

on:
  repository_dispatch:
    types: [veracode-build]

jobs:
  register:
    runs-on: ubuntu-latest
    name: register
    steps:
      - name: Register build
        id: register-build
        uses: veracode/github-actions-integration-helper@main
        with:
          action: registerBuild
          token: ${{ github.event.client_payload.token }}
          appname: ${{ github.event.client_payload.user_config.profile_name }}
          source_repository: ${{ github.event.client_payload.repository.full_name }}
          check_run_id: ${{ github.run_id }}
          check_run_name: ${{ github.workflow }}
          head_sha: ${{ github.event.client_payload.sha }}
          event_type: ${{ github.event.client_payload.event_type }}
          branch: ${{ github.event.client_payload.user_config.sandbox_scan.branch }}
          issue_trigger_flow: ${{ github.event.client_payload.user_config.issue_trigger_flow }}

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.client_payload.sha }}
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn clean package        
    - uses: actions/upload-artifact@v4
      with:
        name: veracode-artifact
        path: target/verademo.war
